apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- name: opa-policy
  files:
  - policies/policy.rego
  - policies/common.rego
  - policies/data.json

generatorOptions:
  disableNameSuffixHash: true

resources:
  - namespace.yaml
  - opa-config.yaml
  - httpbin.yaml
  - ingress.yaml
